language: java
jdk:
  - oraclejdk8

services:
  - docker

before_install:
  - docker/build-and-start.sh docker/

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

after_script:
  - docker/stop-and-remove.sh